import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <a href="">
            <h6>Pepeloper</h6>
          </a>
          <ul>
            <li>
              <a href="">Home</a>
              <a href="">About</a>
              <a href="">Projects</a>
              <a href="">Contact</a>
            </li>
          </ul>
        </header>
        {children}
        <footer></footer>
      </body>
    </html>
  );
}
