import "./globals.css";
import { Inter } from "next/font/google";
import OmegaLogo from "../public/Ω.svg";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <a href="">
            <Image src={OmegaLogo} alt="page logo" />
            <h6>Pepeloper</h6>
          </a>
          <nav>
            <ul>
              <li>
                <a href="">Home</a>
                <a href="">About</a>
                <a href="">Projects</a>
                <a href="">Contact</a>
              </li>
            </ul>
          </nav>
        </header>
        <main>{children}</main>
        <footer>
          <p>
            Maquetado y diseñado con 💛 por{" "}
            <strong>Abdiel Ortega y Esteban Ladino</strong> © 2023
          </p>
        </footer>
      </body>
    </html>
  );
}
